### PR TITLE
Mutable borrowing for problematic vars

### PR DESCRIPTION
**Pull request by marcusnewton1**

### CODE REVIEW

**Comment by marcusnewton1** [comment]
Might be specific to Windows ¯\_(ツ)_/¯

**Comment by maackle** [comment]
Thanks @marcusnewton1, I don't think it's just WIndows, there seems to be some dependency weirdness going on with this version of futures-preview. We can use this for the update to alpha12.

**Comment by maackle** [comment]
Wait, actually I think this is what's already fixed upstream in alpha12. Stay tuned...will update here when we actually get around to updating our futures-preview dependency

**Comment by marcusnewton1** [comment]
@maackle Yes these variables are fixed in alpha-12, so whatever compatibility issue you're running into might be something else

**Comment by marcusnewton1** [comment]
This is a just a hotfix

**Comment by maackle** [comment]
Sorry, I finally took a moment to remember what this problem is all about. holochain-rust uses a slightly older nightly Rust version in our Makefile, `nightly-2018-12-26`. A later nightly version brought about the change to the Pin API. So, you might have luck making sure you have that nightly version installed.

For reference for others having trouble building, what is your `rustc --version`?

**Pull request closed without merging**
